name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm prisma generate
      - run: pnpm format-check
      - run: pnpm lint
